using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace filesync
{
    class WaybackRecover
    {
        //
        // WaybackRecover.CompareHashes();
        //
        // CompareHashes - This was used to compare hashes from two separate synologys to confirm file system integrity.
        //
        // Final integrity verification of the January 2026 NAS migration from ds1019 (oldnas)
        // to ds1525 (newnas). Run once after all sync operations completed to confirm newnas was a perfect copy.
        //
        // Hash files were generated by running md5sum on both NAS devices via SSH:
        // - oldnas hashed its own volumes locally and wrote results to \\newnas\scratch\hash\oldnas-{share}.hash
        // - newnas hashed its own volumes locally and wrote results to \\newnas\scratch\hash\newnas-{share}.hash
        // This approach avoided hashing across the network in both directions simultaneously, which had previously
        // crashed the workstation ethernet driver. Each NAS read its own local disks; only the small hash result
        // files crossed the network.
        //
        // The hash files contain md5sum output format: "hash  path". Paths are normalized by replacing the volume
        // prefix (/volume1/ on oldnas, /volume2/ on newnas) with "/" so paths are comparable across machines.
        // Synology @eaDir entries are excluded - these are DSM-generated thumbnail and metadata directories that
        // exist independently on each NAS and are not part of the migrated data.
        //
        // Result: 801,662 files verified across data, code, media, photo, download, video-source, and video-edit.
        // Zero missing, zero mismatches. One extra file on newnas (a Storage Analyzer symlink that was resolved
        // to a real file by SMB during the copy, and was excluded from the oldnas hash because find -type f skips
        // symlinks). Migration declared complete and verified.
        //
        // DO NOT USE THIS CODE. It is preserved for reference only. The hash files it reads no longer exist and
        // the migration scenario it verified is complete.

        // this was used to compare hashes created on two separate synologys
        //
        // 
        // # run on oldnas (log in with SSH)
        // mkdir /tmp/scratch
        // sudo mount -t cifs //192.168.1.220/scratch /tmp/scratch -o username=john,password=x,vers=2.0
        // find /volume1/data -type f -print0 | xargs -0 md5sum > /tmp/scratch/hash/oldnas-data.hash
        // 
        // # run on newnas (log in with SSH)
        // find /volume2/data -type f -print0 | xargs -0 md5sum > /volume1/scratch/hash/newnas-data.hash
        // 
        // # outputs for comparison (data,code,media,photo,download,video-source,video-edit)
        // \\newnas\scratch\hash\oldnas-data.hash
        // \\newnas\scratch\hash\newnas-data.hash
        // 

        public static void CompareHashes()
        {
            var roots = "data,code,media,photo,download,video-source,video-edit".Split(',').ToArray();
            foreach (var root in roots)
            {
                CompareHashes(root);
            }
        }

        public static void CompareHashes(string rootDir)
        {
            Console.WriteLine("");
            Console.WriteLine(rootDir);
            Console.WriteLine("--------------");

            var oldnasFile = @"\\newnas\scratch\hash\oldnas-{ROOT}.hash".Replace("{ROOT}", rootDir);
            var newnaFile = @"\\newnas\scratch\hash\newnas-{ROOT}.hash".Replace("{ROOT}", rootDir);
            var ignoreToken = "/@eaDir/";
            var oldnasPrefix = "/volume1/";
            var newnasPrefix = "/volume2/";

            Func<string, (string hash, string path)?> parseLine = line =>
            {
                var idx = line.IndexOf(" ");
                if (idx < 0) throw new Exception($"Broken Line: {line}");
                return (line.Substring(0, idx).Trim(), line.Substring(idx + 1).Trim());
            };

            ////Func<string, string> normalizePath = path =>
            ////    path.StartsWith(oldnasPrefix) ? path.Substring(oldnasPrefix.Length) :
            ////    path.StartsWith(newnasPrefix) ? path.Substring(newnasPrefix.Length) :
            ////    path;

            var oldnas = File.ReadAllLines(oldnasFile)
                .Where(l => !l.Contains(ignoreToken))
                .Where(l => !string.IsNullOrEmpty(l))
                .Select(l => l.Replace(oldnasPrefix, "/"))
                .Select(l => l.Replace(newnasPrefix, "/"))
                .Select(l => parseLine(l))
                .Where(t => t.HasValue)
                .Select(t => t.Value)
                .ToDictionary(t => t.path, t => t.hash);

            var newnas = File.ReadAllLines(newnaFile)
                .Where(l => !l.Contains(ignoreToken))
                .Where(l => !string.IsNullOrEmpty(l))
                .Select(l => l.Replace(oldnasPrefix, "/"))
                .Select(l => l.Replace(newnasPrefix, "/"))
                .Select(l => parseLine(l))
                .Where(t => t.HasValue)
                .Select(t => t.Value)
                .ToDictionary(t => t.path, t => t.hash);

            int missing = 0, extra = 0, mismatch = 0, clean = 0;

            foreach (var kvp in oldnas)
            {
                if (!newnas.ContainsKey(kvp.Key))
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"MISSING FROM NEWNAS: {kvp.Key}");
                    missing++;
                }
                else if (newnas[kvp.Key] != kvp.Value)
                {
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.WriteLine($"HASH MISMATCH: {kvp.Key}");
                    mismatch++;
                }
                else
                {
                    clean++;
                }
            }

            foreach (var kvp in newnas)
            {
                if (!oldnas.ContainsKey(kvp.Key))
                {
                    Console.ForegroundColor = ConsoleColor.DarkYellow;
                    Console.WriteLine($"EXTRA ON NEWNAS: {kvp.Key}");
                    extra++;
                }
            }

            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine("--------------");
            Console.WriteLine($"CLEAN:   {clean}");
            Console.WriteLine($"MISSING: {missing}");
            Console.WriteLine($"EXTRA:   {extra}");
            Console.WriteLine($"MISMATCH:{mismatch}");
        }

        //
        // WaybackRecover.ProcessManifest()
        // WaybackRecover - One-time NAS recovery tool, written April 2026 during migration from ds1019 (oldnas) to ds1525 (newnas).
        //
        // Background: oldnas suffered a power failure on January 10, 2026 which caused the volume to go read-only.
        // A filesync migration was already in progress and had been running for several days. The power failure
        // caused File.Copy to leave behind "ghost files" on newnas - files where the metadata (size, timestamps,
        // read-only attribute) was copied from the source but no actual bytes were written. Every subsequent sync
        // run would see these ghost files as already existing and skip them, or fail to overwrite them due to the
        // read-only attribute. This was ultimately diagnosed as a defect in the .NET File.Copy method which does
        // not clean up the destination file on failure.
        //
        // Manifests were created of wayback files that failed to copy/migrate using filesync, such that the wayback
        // could be manually patched from the nearest temporally wayback, provided all other files were identical.
        //
        // ProcessManifest: Reads a log file of "FILE NOT COPIED DUE TO ERROR:" lines produced by filesync running
        // with retries:off. Groups the failed files by their top-level project folder within each wayback snapshot
        // (e.g. \\newnas\z-wayback\code\asof-2022-12\__52week-program). For each failed group, searches sibling
        // wayback snapshots ordered by closest date to find a valid donor - a snapshot where the project folder is
        // byte-for-byte identical except for the presence of the missing files. The comparison is strict: every file
        // must match on size and timestamp (with 5-second FAT/exFAT tolerance), the candidate must have no extra
        // files beyond the known missing ones, and the known missing files must all be present in the candidate.
        // If a valid donor is found, emits a filesync command to recover the folder. If no donor qualifies, reports
        // unrecoverable. Noise files (Thumbs.db, desktop.ini, .flutter-plugins) are excluded from comparison.
        //
        // This tool was ultimately not needed for most failures. The root cause turned out to be ghost files with
        // read-only attributes blocking overwrite - fixed by adding File.SetAttributes(to, FileAttributes.Normal)
        // in the filesync retry loop. After that fix, rerunning the sync against oldnas directly recovered virtually
        // everything. The few genuinely unrecoverable files were git objects in old wayback snapshots, which are
        // covered by GitHub and not worth recovering. ProcessManifest was used successfully to recover the mekka
        // ASP project folders (ancient FrontPage-era code with no other backup) from sibling snapshots.
        //
        // DO NOT USE THIS CODE. It is preserved for reference only. The recovery scenario it addresses is
        // specific to the January 2026 migration and has no ongoing operational purpose.
        //
        const string ERROR_PREFIX = "FILE NOT COPIED DUE TO ERROR: ";

        public static void ProcessManifest(string manifestFileName, Dictionary<string, string> options)
        {
            var errorLines = File.ReadAllLines(manifestFileName)
                .Where(l => l.StartsWith(ERROR_PREFIX))
                .Select(l => l.Substring(ERROR_PREFIX.Length).Trim())
                .ToList();

            if (!errorLines.Any())
            {
                Console.WriteLine("No actionable lines in manifest.");
                return;
            }

            var groups = errorLines
                .GroupBy(path => GetRootFolder(path))
                .Where(g => g.Key != null)
                .ToList();

            Console.WriteLine($"Found {groups.Count} root folder(s) with errors.");

            var parallelOptions = new ParallelOptions();
            if (options.ContainsKey("threads"))
                parallelOptions.MaxDegreeOfParallelism = int.Parse(options["threads"]);

            Parallel.ForEach(groups, parallelOptions, group =>
            {
                var sb = new StringBuilder();
                var rootFolder = group.Key;

                var missingFiles = new HashSet<string>(
                    group.Select(p => p.Substring(rootFolder.Length).TrimStart('\\')),
                    StringComparer.Ordinal);

                sb.AppendLine();
                sb.AppendLine($"PROCESSING: {rootFolder}");
                sb.AppendLine($"  Missing files: {missingFiles.Count}");

                var parts = rootFolder.Split('\\');
                var snapshotPart = parts[5];
                var categoryPath = string.Join("\\", parts.Take(5));
                var rootName = parts[6];

                if (!TryParseSnapshot(snapshotPart, out var targetDate))
                {
                    sb.AppendLine($"  SKIPPED: could not parse snapshot date from {snapshotPart}");
                    Console.Write(sb.ToString());
                    return;
                }

                var siblingDirs = Directory.GetDirectories(categoryPath)
                    .Select(d => d.Split('\\').Last())
                    .Where(d => d.StartsWith("asof-"))
                    .Where(d => d != snapshotPart)
                    .Select(d => new { name = d, date = TryParseSnapshotDate(d) })
                    .Where(d => d.date.HasValue)
                    .OrderBy(d => Math.Abs((d.date.Value - targetDate).TotalHours))
                    .ToList();

                if (!siblingDirs.Any())
                {
                    sb.AppendLine("  UNRECOVERABLE: no sibling snapshots found");
                    Console.Write(sb.ToString());
                    return;
                }

                bool recovered = false;
                foreach (var sibling in siblingDirs)
                {
                    var candidatePath = categoryPath + '\\' + sibling.name + '\\' + rootName;

                    if (!Directory.Exists(candidatePath))
                    {
                        sb.AppendLine($"  SKIP [{sibling.name}]: root folder not present");
                        continue;
                    }

                    sb.Append($"  Comparing [{sibling.name}]... ");

                    var reason = CompareDirectories(rootFolder, candidatePath, missingFiles);
                    if (reason != null)
                    {
                        sb.AppendLine($"FAIL: {reason}");
                        continue;
                    }

                    sb.AppendLine("MATCH");
                    sb.AppendLine($"  filesync from:\"{candidatePath}\" to:\"{rootFolder}\" prompt:false");
                    recovered = true;
                    break;
                }

                if (!recovered)
                    sb.AppendLine("  UNRECOVERABLE: no matching candidate found");

                Console.Write(sb.ToString());
            });
        }

        static string CompareDirectories(string targetPath, string candidatePath, HashSet<string> missingFiles)
        {
            var targetFiles = GetAllFiles(targetPath)
                .Where(kvp => !missingFiles.Contains(kvp.Key))
                .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);

            var candidateFiles = GetAllFiles(candidatePath);

            // parallel compare - first mismatch wins via ConcurrentBag
            var failures = new ConcurrentBag<string>();

            Parallel.ForEach(targetFiles.Keys, (rel, state) =>
            {
                if (state.IsStopped) return;

                if (!candidateFiles.ContainsKey(rel))
                {
                    failures.Add($"candidate missing file: {rel}");
                    state.Stop();
                    return;
                }

                var tf = targetFiles[rel];
                var cf = candidateFiles[rel];

                if (tf.Length != cf.Length)
                {
                    failures.Add($"size mismatch: {rel}");
                    state.Stop();
                    return;
                }

                if (Math.Abs((tf.LastWriteTimeUtc - cf.LastWriteTimeUtc).TotalSeconds) > 5)
                {
                    failures.Add($"timestamp mismatch: {rel}");
                    state.Stop();
                    return;
                }
            });

            if (failures.Any())
                return failures.First();

            // candidate extras must be exactly the missing files
            var candidateExtras = candidateFiles.Keys.Except(targetFiles.Keys).ToHashSet();

            var unexpectedExtras = candidateExtras.Except(missingFiles).ToList();
            if (unexpectedExtras.Any())
                return $"candidate has unexpected extra file: {unexpectedExtras.First()}";

            var missingFromCandidate = missingFiles.Except(candidateExtras).ToList();
            if (missingFromCandidate.Any())
                return $"candidate does not have missing file: {missingFromCandidate.First()}";

            return null;
        }

        static Dictionary<string, FileInfo> GetAllFiles(string root)
        {
            var result = new ConcurrentDictionary<string, FileInfo>(StringComparer.Ordinal);
            if (!Directory.Exists(root)) return result.ToDictionary(k => k.Key, k => k.Value);

            var files = Directory.GetFiles(root, "*", SearchOption.AllDirectories);

            Parallel.ForEach(files, f =>
            {
                var rel = f.Substring(root.Length).TrimStart('\\');
                if (rel.EndsWith("Thumbs.db", StringComparison.OrdinalIgnoreCase)) return;
                if (rel.EndsWith("desktop.ini", StringComparison.OrdinalIgnoreCase)) return;
                if (rel.EndsWith(".flutter-plugins", StringComparison.OrdinalIgnoreCase)) return;
                if (rel.EndsWith(".flutter-plugins-dependencies", StringComparison.OrdinalIgnoreCase)) return;
                result[rel] = new FileInfo(f);
            });

            return result.ToDictionary(k => k.Key, k => k.Value, StringComparer.Ordinal);
        }

        static string GetRootFolder(string path)
        {
            var parts = path.Split('\\');
            if (parts.Length < 7) return null;
            if (!parts[5].StartsWith("asof-")) return null;
            return string.Join("\\", parts.Take(7));
        }

        static bool TryParseSnapshot(string snapshot, out DateTime date)
        {
            date = default;
            var d = TryParseSnapshotDate(snapshot);
            if (!d.HasValue) return false;
            date = d.Value;
            return true;
        }

        static DateTime? TryParseSnapshotDate(string snapshot)
        {
            try
            {
                var datePart = snapshot.Substring(snapshot.IndexOf('-') + 1) + "-01";
                if (DateTime.TryParse(datePart, out var d)) return d;
            }
            catch { }
            return null;
        }
    }
}